name: Comment on issues
on:
  issues:
    type: [opened]
jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - name: comment issues
      uses: actions/github-script@0.8.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.create.comment({
          issue_number: context.issue.number,
          owner: context.repo.owner,
          repo: context.repo.repo,
          body: "🎉 You've created this issue comment using GitHub Script!!!"
          })
